@extends('errors.layout')
@section('code', '404')
@section('title', 'Halaman Tidak Ditemukan')
@section('description', 'Halaman yang Anda cari tidak ada atau sudah dipindahkan. Periksa kembali URL atau kembali ke dashboard.')
@section('icon', 'fa-solid fa-map-location-dot')
@section('icon-bg', 'bg-amber-500')